---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    Cover Image:
    Images:
    - Fullwidth-image:
    - Half-Image-left:
      Half-image-right:
    - Image:
    Project Description:
    - Fullwidth-image:
    - Half-Image-left:
      Half-image-right:
    - Image:
    Expertise:
    - Skill:
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
