---
title: ANA LUCÍA DESPRES
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    Images:
    - Fullwidth-image: 
    - Half-Image-left: 
      Half-image-right: 
    - Image: 
    Project Description:
    - Fullwidth-image: 
    - Half-Image-left: 
      Half-image-right: 
    - Image: 
    Expertise:
    - Skill text: 
    Cover Image: 
email: your-email@example.com
description: Art Director, Visual UXUI Designer, Experience Creator and Art Observer
  focused in Real Estate, Architecture and Luxury brands.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
theme: minima
sass:
  sass_dir: "./_scss"
plugins:
- jekyll-feed
